package com.example.myweather.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF36618E)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD2E4FF)
val LightOnPrimaryContainer = Color(0xFF001D36)
val LightSecondary = Color(0xFF4A99A8)
val LightBackground = Color(0xFFF7F9FC)
val LightSurface = Color(0xFFF7F9FC)
val LightSurfaceContainer = Color(0xFFE7EDF5)
val LightSurfaceContainerHigh = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFE4E7EC)
val LightOnSurface = Color(0xFF191C20)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightOutline = Color(0xFF73777F)
val LightOutlineVariant = Color(0xFFC3C7CF)
val LightError = Color(0xFFBA1A1A)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

val DarkPrimary = Color(0xFFA2C9FE)
val DarkOnPrimary = Color(0xFF003257)
val DarkPrimaryContainer = Color(0xFF1D4874)
val DarkOnPrimaryContainer = Color(0xFFD4E3FF)
val DarkSecondary = Color(0xFFA8CFD8)
val DarkBackground = Color(0xFF111418)
val DarkSurface = Color(0xFF111418)
val DarkSurfaceContainer = Color(0xFF22262B)
val DarkSurfaceContainerHigh = Color(0xFF1D2024)
val DarkSurfaceVariant = Color(0xFF26292E)
val DarkOnSurface = Color(0xFFE1E2E8)
val DarkOnSurfaceVariant = Color(0xFFC3C6CF)
val DarkOutline = Color(0xFF8D9199)
val DarkOutlineVariant = Color(0xFF43474E)
val DarkError = Color(0xFFFFB4AB)
val DarkErrorContainer = Color(0xFF3B2725)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
